
import React, { useState } from 'react';

const LegalFooter: React.FC = () => {
    const [modalContent, setModalContent] = useState<{ title: string; content: string } | null>(null);

    const policies = {
        terms: {
            title: 'Terms of Service',
            content: `
Welcome to Beauty Lab. By using our services, you agree to the following terms:
1. Nature of Service: Beauty Lab provides AI-powered image analysis and generation. Results are generated by AI models and should be used for entertainment purposes only.
2. User Content: You are responsible for the images you upload. You must have the right to use such images and they must not violate any laws or third-party rights.
3. Account & Credits: Credits purchased are linked to your device/account. You are responsible for maintaining the security of your access.
4. Disclaimer: We do not guarantee the accuracy or reliability of AI-generated results. The service is provided "as is" without warranties of any kind.
      `
        },
        privacy: {
            title: 'Privacy Policy',
            content: `
At Beauty Lab, your privacy is our priority:
1. Data Collection: We collect device identifiers and images you upload for the sole purpose of providing AI analysis.
2. Data Usage: Uploaded images are processed by AI models (Google Gemini) and are not used for any other purposes.
3. Data Storage: We store your credit balance and order history securely in our database. We do not sell your personal data to third parties.
4. Security: We implement industry-standard security measures to protect your information.
      `
        },
        refund: {
            title: 'Refund Policy',
            content: `
Our Refund Policy ensures a fair experience:
1. Digital Goods: Since our service provides instant AI processing and digital credits, refunds are generally not provided once credits have been used.
2. Technical Issues: If you encounter a technical failure where credits were deducted but no result was generated, please contact us for a manual credit adjustment.
3. Satisfaction: If you are unsatisfied with the service, please reach out to our support team. We value your feedback and will handle requests on a case-by-case basis.
4. Contact: For refund inquiries, please email us at 408457641@qq.com.
      `
        }
    };

    return (
        <footer className="mt-12 mb-8 pb-10 border-t border-gray-100 pt-8 px-6">
            <div className="flex flex-wrap justify-center gap-x-6 gap-y-2 text-xs text-gray-400 font-medium lowercase">
                <button onClick={() => setModalContent(policies.terms)} className="hover:text-pink-500 transition-colors">Terms of Service</button>
                <button onClick={() => setModalContent(policies.privacy)} className="hover:text-pink-500 transition-colors">Privacy Policy</button>
                <button onClick={() => setModalContent(policies.refund)} className="hover:text-pink-500 transition-colors">Refund Policy</button>
                <a href="mailto:408457641@qq.com" className="hover:text-pink-500 transition-colors">Contact Us</a>
            </div>
            <p className="text-center text-[10px] text-gray-300 mt-4 uppercase tracking-widest">
                &copy; {new Date().getFullYear()} Beauty Lab AI. All Rights Reserved.
            </p>

            {/* Simplified Legal Modal */}
            {modalContent && (
                <div className="fixed inset-0 z-[100] bg-black/60 backdrop-blur-sm flex items-center justify-center p-4 overflow-y-auto">
                    <div className="bg-white rounded-3xl w-full max-w-lg max-h-[80vh] flex flex-col shadow-2xl animate-in fade-in zoom-in duration-300">
                        <div className="p-6 border-b border-gray-50 flex justify-between items-center">
                            <h3 className="text-xl font-bold text-gray-800">{modalContent.title}</h3>
                            <button
                                onClick={() => setModalContent(null)}
                                className="w-8 h-8 rounded-full bg-gray-50 flex items-center justify-center text-gray-400 hover:bg-pink-50 hover:text-pink-500 transition-all"
                            >
                                ✕
                            </button>
                        </div>
                        <div className="p-6 overflow-y-auto text-sm text-gray-600 leading-relaxed whitespace-pre-wrap">
                            {modalContent.content}
                        </div>
                        <div className="p-6 border-t border-gray-50 flex justify-end">
                            <button
                                onClick={() => setModalContent(null)}
                                className="px-6 py-2 bg-pink-500 text-white rounded-full font-bold shadow-lg shadow-pink-200 active:scale-95 transition-all"
                            >
                                Got it
                            </button>
                        </div>
                    </div>
                </div>
            )}
        </footer>
    );
};

export default LegalFooter;
