-- ==========================================
-- AI 成本优化与监控数据库表结构 (Supabase)
-- ==========================================

-- 1. AI 结果缓存表 (用于重复请求提速与省钱)
CREATE TABLE IF NOT EXISTS gemini_cache (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    input_hash TEXT UNIQUE NOT NULL, -- 输入参数与图片的 SHA-256 特征指纹
    result TEXT NOT NULL,           -- AI 返回的完整结果内容 (JSON 或 Base64)
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 为缓存增加哈希索引，提升高并发下的检索速度
CREATE INDEX IF NOT EXISTS idx_gemini_cache_hash ON gemini_cache(input_hash);

-- 2. AI 使用量日志表 (用于监控分析与账单核对)
CREATE TABLE IF NOT EXISTS gemini_usage_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action TEXT NOT NULL,           -- 业务动作 (如 analyze, tryOn)
    model_id TEXT NOT NULL,         -- 实际调用的模型 ID
    prompt_tokens INT,              -- 输入 Token 数
    completion_tokens INT,          -- 输出 Token 数
    total_tokens INT,               -- 总消耗 Token 数
    duration_ms INT,                -- API 接口总耗时 (毫秒)
    status TEXT NOT NULL,           -- 状态: success 或 error
    error_message TEXT,             -- 如果失败，记录具体错误
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 增加按动作分布和时间的索引，利于后续制作统计图表
CREATE INDEX IF NOT EXISTS idx_gemini_usage_action ON gemini_usage_logs(action);
CREATE INDEX IF NOT EXISTS idx_gemini_usage_created ON gemini_usage_logs(created_at);
